services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kornelian
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./kornelian.com.pem:/app/kornelian.com.pem
      - ./kornelian.com.key:/app/kornelian.com.key
    restart: unless-stopped
    